
import { Technology } from '@/types/technology';

export const ADDITIONAL_TECHNOLOGIES: Technology[] = [
  {
    id: 'fusion-drive',
    name: '核聚变推进系统',
    description: '利用受控核聚变反应产生巨大能量的革命性推进技术，可为未来星际飞行提供无与伦比的推力。',
    history: '核聚变推进概念始于20世纪中期，但直到2027年中国科学院才实现了首个可控聚变微型反应堆，随后应用于航天领域。',
    currentProgress: '目前已成功研发第二代原型机，实现了5分钟稳定运行，推力达到传统化学火箭的10倍。',
    currentApplications: [
      '深空探测器主推进系统',
      '行星际飞行器动力源',
      '大型空间站姿态控制',
    ],
    futureImprovements: [
      '延长稳定运行时间',
      '提高能量转化效率',
      '减少辐射屏蔽重量',
      '开发更紧凑的反应堆设计',
    ],
    pros: [
      '超高能量密度',
      '极高推力-重量比',
      '燃料丰富且易获取',
      '运行时间长',
    ],
    cons: [
      '技术极其复杂',
      '需要强大的辐射屏蔽',
      '启动能耗巨大',
      '成本高昂',
    ],
    image: 'https://images.unsplash.com/photo-1454789548928-9efd52dc4031?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: '推进系统',
  },
  {
    id: 'quantum-computing',
    name: '量子计算系统',
    description: '利用量子力学原理的计算系统，能够瞬间解决传统计算机需要数千年才能解决的复杂问题。',
    history: '量子计算理论始于20世纪80年代，中国于2022年实现了首台100量子比特的实用量子计算机，并于2026年将其应用于航天领域。',
    currentProgress: '已部署256量子比特系统于轨道控制中心，可实时计算数百艘航天器的最优轨道。',
    currentApplications: [
      '复杂轨道力学计算',
      '多体问题模拟',
      '天体物理学研究',
    ],
    futureImprovements: [
      '提升量子比特数量',
      '提高量子相干时间',
      '减少量子纠错开销',
      '研发航天专用算法',
    ],
    pros: [
      '计算速度远超传统计算机',
      '可解决传统计算机无法解决的问题',
      '能耗相对较低',
      '体积小重量轻',
    ],
    cons: [
      '量子退相干问题',
      '编程复杂度高',
      '需要极低温环境',
      '硬件脆弱',
    ],
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: '计算系统',
  },
  {
    id: 'artificial-gravity',
    name: '人工重力系统',
    description: '通过旋转或高级场技术创造类似地球重力的环境，解决长期太空飞行中的失重问题。',
    history: '人工重力概念可追溯到20世纪初，但实用系统直到2025年才由中国工程师在空间站"天宫"二号上成功测试。',
    currentProgress: '已在月球基地实现0.38g人工重力环境，并在火星飞行器原型上测试了完整系统。',
    currentApplications: [
      '深空探索飞船生活区',
      '月球基地居住舱',
      '空间站训练区域',
    ],
    futureImprovements: [
      '减少系统重量',
      '开发非旋转式人工重力技术',
      '实现重力梯度可调',
      '降低能源消耗',
    ],
    pros: [
      '防止宇航员肌肉萎缩和骨质流失',
      '改善心血管健康',
      '简化日常生活操作',
      '降低长期健康风险',
    ],
    cons: [
      '系统庞大复杂',
      '旋转式系统可能导致眩晕',
      '能源消耗高',
      '工程挑战大',
    ],
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: '生命支持系统',
  },
  {
    id: 'space-elevator',
    name: '太空电梯',
    description: '连接地球表面和地球同步轨道的超长结构，可大幅降低将物资送入太空的成本和环境影响。',
    history: '太空电梯概念可追溯到20世纪初的科幻小说，但工程可行性研究始于21世纪初。中国于2028年启动了首个原型测试项目。',
    currentProgress: '已完成碳纳米管复合材料缆绳的实验室测试，并在高空进行了微型原型的悬挂测试。',
    currentApplications: [
      '理论阶段，尚无实际应用',
      '材料科学研究',
      '空间动力学模拟',
    ],
    futureImprovements: [
      '开发更强韧的缆绳材料',
      '解决轨道碎片影响问题',
      '优化爬升器设计',
      '降低总体工程成本',
    ],
    pros: [
      '极大降低入轨成本',
      '无需火箭发射的环保优势',
      '可持续运行多年',
      '允许大规模货物运输',
    ],
    cons: [
      '材料强度要求极高',
      '易受太空碎片威胁',
      '建造成本巨大',
      '需要国际协作',
    ],
    image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: '基础设施',
  },
  {
    id: 'laser-communication',
    name: '激光通信系统',
    description: '使用高能激光束传输数据的通信技术，相比传统无线电通信具有更高的带宽和安全性。',
    history: '激光通信在航天领域的应用始于21世纪初，中国于2023年实现了首次月地激光通信实验，传输速率达到10Gbps。',
    currentProgress: '已实现火星-地球的稳定激光通信链路，传输速率达到2Gbps，为传统通信的100倍。',
    currentApplications: [
      '深空探测器高带宽通信',
      '空间站与地面的大容量数据传输',
      '卫星星座内部通信网络',
    ],
    futureImprovements: [
      '提高激光聚焦精度',
      '开发全天候工作能力',
      '扩大通信距离',
      '降低功耗',
    ],
    pros: [
      '极高数据传输速率',
      '较低的功耗要求',
      '难以被截获的安全优势',
      '不受频谱管制限制',
    ],
    cons: [
      '受大气条件影响',
      '需要精确的指向控制',
      '通信站点有限',
      '初期建设成本高',
    ],
    image: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
    category: '通讯系统',
  },
];
